export const ArrayChonNhieu = [
    'Ảnh' ,
    'Xưng hô' ,
    'Họ và đệm' ,
    'Tên' ,
    'Phòng ban' ,
    'Chức danh' ,
    'ĐT di dộng' ,
    'ĐT cơ quan' ,
    'Nguồn gốc' ,
    'Loại tiềm năng' ,
    'Zalo' ,
    'Email cá nhân' ,
    'Email cơ quan' ,
    'Tổ chức' ,
    'Mã số thuế' ,
    'Tài khoản ngân hàng' ,
    'Mở tại ngân hàng' ,
    'Ngày thành lập' ,
    'Loại hình' ,
    'Lĩnh vực' ,
    'Ngành nghề' ,
    'Doanh thu' ,
    'Quốc gia' ,
    'Tỉnh thành' ,
    'Quận huyện' ,
    'Phường xã' ,
    'Số nhà' ,
    'Mã vùng' ,
    'Mô tả' ,
    'Dùng chung' ,
  ];