// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fresher_test_ASP.NET_Core_Web_API.Models;

#nullable disable

namespace fresher_test_ASP.NET_Core_Web_API.Migrations
{
    [DbContext(typeof(customerDatabaseContext))]
    partial class customerDatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.customer", b =>
                {
                    b.Property<string>("_id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("anh")
                        .HasColumnType("longtext");

                    b.Property<string>("chucdanh")
                        .HasColumnType("longtext");

                    b.Property<string>("doanhthu")
                        .HasColumnType("longtext");

                    b.Property<string>("dtcoquan")
                        .HasColumnType("longtext");

                    b.Property<string>("dtdidong")
                        .HasColumnType("longtext");

                    b.Property<bool>("dungchung")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("emailcanhan")
                        .HasColumnType("longtext");

                    b.Property<string>("emailcoquan")
                        .HasColumnType("longtext");

                    b.Property<string>("hovadem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("linhvuc")
                        .HasColumnType("longtext");

                    b.Property<string>("loaihinh")
                        .HasColumnType("longtext");

                    b.Property<string>("masothue")
                        .HasColumnType("longtext");

                    b.Property<string>("mota")
                        .HasColumnType("longtext");

                    b.Property<string>("motainganhang")
                        .HasColumnType("longtext");

                    b.Property<string>("nganhnghe")
                        .HasColumnType("longtext");

                    b.Property<string>("ngaythanhlap")
                        .HasColumnType("longtext");

                    b.Property<string>("nguongoc")
                        .HasColumnType("longtext");

                    b.Property<string>("phongban")
                        .HasColumnType("longtext");

                    b.Property<string>("phuongxa")
                        .HasColumnType("longtext");

                    b.Property<string>("quanhuyen")
                        .HasColumnType("longtext");

                    b.Property<string>("quocgia")
                        .HasColumnType("longtext");

                    b.Property<string>("sonha")
                        .HasColumnType("longtext");

                    b.Property<string>("taikhoannganhang")
                        .HasColumnType("longtext");

                    b.Property<string>("ten")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("tinhthanhpho")
                        .HasColumnType("longtext");

                    b.Property<string>("tochuc")
                        .HasColumnType("longtext");

                    b.Property<string>("xungho")
                        .HasColumnType("longtext");

                    b.Property<string>("zalo")
                        .HasColumnType("longtext");

                    b.HasKey("_id");

                    b.ToTable("customer");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.filter", b =>
                {
                    b.Property<int>("filterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("filterId");

                    b.ToTable("filter");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.filterContent", b =>
                {
                    b.Property<int>("filterContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("chucdanhCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("chucdanhString")
                        .HasColumnType("longtext");

                    b.Property<string>("doanhthuCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("doanhthuString")
                        .HasColumnType("longtext");

                    b.Property<string>("dtcoquanCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("dtcoquanString")
                        .HasColumnType("longtext");

                    b.Property<string>("dtdidongCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("dtdidongString")
                        .HasColumnType("longtext");

                    b.Property<string>("dungchungCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("dungchungString")
                        .HasColumnType("longtext");

                    b.Property<string>("emailcanhanCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("emailcanhanString")
                        .HasColumnType("longtext");

                    b.Property<string>("emailcoquanCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("emailcoquanString")
                        .HasColumnType("longtext");

                    b.Property<int>("filterId")
                        .HasColumnType("int");

                    b.Property<string>("hovademCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("hovademString")
                        .HasColumnType("longtext");

                    b.Property<string>("linhvucCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("linhvucString")
                        .HasColumnType("longtext");

                    b.Property<string>("loaihinhCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("loaihinhString")
                        .HasColumnType("longtext");

                    b.Property<string>("loaitiemnangCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("loaitiemnangString")
                        .HasColumnType("longtext");

                    b.Property<string>("masothueCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("masothueString")
                        .HasColumnType("longtext");

                    b.Property<string>("motaCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("motaString")
                        .HasColumnType("longtext");

                    b.Property<string>("motainganhangCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("motainganhangString")
                        .HasColumnType("longtext");

                    b.Property<string>("nganhngheCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("nganhngheString")
                        .HasColumnType("longtext");

                    b.Property<string>("ngaythanhlapCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("ngaythanhlapString")
                        .HasColumnType("longtext");

                    b.Property<string>("nguongocCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("nguongocString")
                        .HasColumnType("longtext");

                    b.Property<string>("phongbanCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("phongbanString")
                        .HasColumnType("longtext");

                    b.Property<string>("phuongxaCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("phuongxaString")
                        .HasColumnType("longtext");

                    b.Property<string>("quanhuyenCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("quanhuyenString")
                        .HasColumnType("longtext");

                    b.Property<string>("quocgiaCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("quocgiaString")
                        .HasColumnType("longtext");

                    b.Property<string>("sonhaCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("sonhaString")
                        .HasColumnType("longtext");

                    b.Property<string>("taikhoannganhangCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("taikhoannganhangString")
                        .HasColumnType("longtext");

                    b.Property<string>("tenCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("tenString")
                        .HasColumnType("longtext");

                    b.Property<string>("theCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("theString")
                        .HasColumnType("longtext");

                    b.Property<string>("tinhthanhphoCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("tinhthanhphoString")
                        .HasColumnType("longtext");

                    b.Property<string>("tochucCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("tochucString")
                        .HasColumnType("longtext");

                    b.Property<string>("xunghoCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("xunghoString")
                        .HasColumnType("longtext");

                    b.Property<string>("zaloCondition")
                        .HasColumnType("longtext");

                    b.Property<string>("zaloString")
                        .HasColumnType("longtext");

                    b.HasKey("filterContentId");

                    b.HasIndex("filterId")
                        .IsUnique();

                    b.ToTable("filterContent");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.history", b =>
                {
                    b.Property<int>("historyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("historyContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("historyId");

                    b.HasIndex("customerId");

                    b.ToTable("history");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.loaitiemnang", b =>
                {
                    b.Property<int>("loaitiemnangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("loaitiemnangContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("loaitiemnangId");

                    b.HasIndex("customerId");

                    b.ToTable("loaitiemnang");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.the", b =>
                {
                    b.Property<int>("theId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("customerId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("theContent")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("theId");

                    b.HasIndex("customerId");

                    b.ToTable("the");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.filterContent", b =>
                {
                    b.HasOne("fresher_test_ASP.NET_Core_Web_API.Models.filter", "filter")
                        .WithOne("filterContent")
                        .HasForeignKey("fresher_test_ASP.NET_Core_Web_API.Models.filterContent", "filterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("filter");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.history", b =>
                {
                    b.HasOne("fresher_test_ASP.NET_Core_Web_API.Models.customer", "customer")
                        .WithMany("history")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.loaitiemnang", b =>
                {
                    b.HasOne("fresher_test_ASP.NET_Core_Web_API.Models.customer", "customer")
                        .WithMany("loaitiemnang")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.the", b =>
                {
                    b.HasOne("fresher_test_ASP.NET_Core_Web_API.Models.customer", "customer")
                        .WithMany("the")
                        .HasForeignKey("customerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("customer");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.customer", b =>
                {
                    b.Navigation("history");

                    b.Navigation("loaitiemnang");

                    b.Navigation("the");
                });

            modelBuilder.Entity("fresher_test_ASP.NET_Core_Web_API.Models.filter", b =>
                {
                    b.Navigation("filterContent")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
