//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB08.AMIS.COMMON.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB08.AMIS.COMMON.Resources.MISAResource", typeof(MISAResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecretConnectionString.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tô Nguyễn Đức Mạnh.
        /// </summary>
        public static string Default_CreatedBy_User {
            get {
                return ResourceManager.GetString("Default_CreatedBy_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liễu Thị Oanh.
        /// </summary>
        public static string Default_ModifiedBy_User {
            get {
                return ResourceManager.GetString("Default_ModifiedBy_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something wrong when try to delete this record.
        /// </summary>
        public static string DevMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("DevMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is existed, please try another code.
        /// </summary>
        public static string DevMsg_Employee_DuplicatedCode {
            get {
                return ResourceManager.GetString("DevMsg_Employee_DuplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sever has error when try to do this request..
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert record to databse failed.
        /// </summary>
        public static string DevMsg_InsertFailed {
            get {
                return ResourceManager.GetString("DevMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update record to database failed.
        /// </summary>
        public static string DevMsg_UpdatedFailed {
            get {
                return ResourceManager.GetString("DevMsg_UpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fileds of this request is not accepted.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e009.
        /// </summary>
        public static string MoreInfo_DeleteFailed {
            get {
                return ResourceManager.GetString("MoreInfo_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e002.
        /// </summary>
        public static string MoreInfo_Employee_DupplicatedCode {
            get {
                return ResourceManager.GetString("MoreInfo_Employee_DupplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e001.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e007.
        /// </summary>
        public static string MoreInfo_InsertFailed {
            get {
                return ResourceManager.GetString("MoreInfo_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e008.
        /// </summary>
        public static string MoreInfo_UpdatedFailed {
            get {
                return ResourceManager.GetString("MoreInfo_UpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e003.
        /// </summary>
        public static string MoreInfo_ValidateFailed {
            get {
                return ResourceManager.GetString("MoreInfo_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MySQLConnectionString.
        /// </summary>
        public static string MyConnectionString {
            get {
                return ResourceManager.GetString("MyConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v_id.
        /// </summary>
        public static string Param_ID {
            get {
                return ResourceManager.GetString("Param_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v_PageNumber.
        /// </summary>
        public static string Param_PageNumber {
            get {
                return ResourceManager.GetString("Param_PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v_PageSize.
        /// </summary>
        public static string Param_PageSize {
            get {
                return ResourceManager.GetString("Param_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to v_Search.
        /// </summary>
        public static string Param_Search {
            get {
                return ResourceManager.GetString("Param_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteManyRecord.
        /// </summary>
        public static string Proc_Delete_ManyRecord {
            get {
                return ResourceManager.GetString("Proc_Delete_ManyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_DeleteOneRecord.
        /// </summary>
        public static string Proc_Delete_OneRecord {
            get {
                return ResourceManager.GetString("Proc_Delete_OneRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_ExportAll.
        /// </summary>
        public static string Proc_ExportToExcel {
            get {
                return ResourceManager.GetString("Proc_ExportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetByID.
        /// </summary>
        public static string Proc_Get_ByID {
            get {
                return ResourceManager.GetString("Proc_Get_ByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetDuplicateCode.
        /// </summary>
        public static string Proc_Get_DupplicateCode {
            get {
                return ResourceManager.GetString("Proc_Get_DupplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetMaxCode.
        /// </summary>
        public static string Proc_Get_MaxCode {
            get {
                return ResourceManager.GetString("Proc_Get_MaxCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetAll.
        /// </summary>
        public static string Proc_GetAll {
            get {
                return ResourceManager.GetString("Proc_GetAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_GetDuplicateCode.
        /// </summary>
        public static string Proc_GetDupplicateCode {
            get {
                return ResourceManager.GetString("Proc_GetDupplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_PostOneRecord.
        /// </summary>
        public static string Proc_InsertOne {
            get {
                return ResourceManager.GetString("Proc_InsertOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_{0}_PutOneRecord.
        /// </summary>
        public static string Proc_Put_OneRecord {
            get {
                return ResourceManager.GetString("Proc_Put_OneRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_GetPaging.
        /// </summary>
        public static string ProcGetEmployeeFilter {
            get {
                return ResourceManager.GetString("ProcGetEmployeeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra khi cố gắng xóa trường này, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_DeleteFailed {
            get {
                return ResourceManager.GetString("UserMsg_DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống, vui lòng sử dụng mã khác.
        /// </summary>
        public static string UserMsg_Employee_DuplicatedCode {
            get {
                return ResourceManager.GetString("UserMsg_Employee_DuplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ với MISA để được hỗ trợ..
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thêm mới thất bại, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_InsertFailed {
            get {
                return ResourceManager.GetString("UserMsg_InsertFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sửa thất bại, vui lòng kiểm tra lại.
        /// </summary>
        public static string UserMsg_UpdatedFailed {
            get {
                return ResourceManager.GetString("UserMsg_UpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có một hoặc nhiều trường dữ liệu bị lỗi, vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
    }
}
