-- MySQL Script generated by MySQL Workbench
-- Fri Jul 15 16:16:56 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema batdongsan
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `batdongsan` ;

-- -----------------------------------------------------
-- Schema batdongsan
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `batdongsan` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `batdongsan` ;

-- -----------------------------------------------------
-- Table `batdongsan`.`Doanhnghiep`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Doanhnghiep` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Doanhnghiep` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `ten` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 400
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Duan`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Duan` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Duan` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  `giam2` VARCHAR(1000) NULL DEFAULT NULL,
  `dientich` VARCHAR(1000) NULL DEFAULT NULL,
  `socanho` VARCHAR(1000) NULL DEFAULT NULL,
  `sonhatoa` VARCHAR(1000) NULL DEFAULT NULL,
  `diachi` VARCHAR(1000) NULL DEFAULT NULL,
  `congty` VARCHAR(1000) NULL DEFAULT NULL,
  `tinhtrang` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 361
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Nhadatban`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Nhadatban` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Nhadatban` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  `gia` VARCHAR(1000) NULL DEFAULT NULL,
  `giam2` VARCHAR(1000) NULL DEFAULT NULL,
  `dientich` VARCHAR(1000) NULL DEFAULT NULL,
  `diachi` VARCHAR(1000) NULL DEFAULT NULL,
  `ngaydangbai` VARCHAR(1000) NULL DEFAULT NULL,
  `nenxem` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 595
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Nhadatchothue`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Nhadatchothue` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Nhadatchothue` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  `gia` VARCHAR(1000) NULL DEFAULT NULL,
  `giam2` VARCHAR(1000) NULL DEFAULT NULL,
  `dientich` VARCHAR(1000) NULL DEFAULT NULL,
  `diachi` VARCHAR(1000) NULL DEFAULT NULL,
  `ngaydangbai` VARCHAR(1000) NULL DEFAULT NULL,
  `nenxem` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 368
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Nhamoigioi`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Nhamoigioi` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Nhamoigioi` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `ten` VARCHAR(1000) NULL DEFAULT NULL,
  `diachi` VARCHAR(1000) NULL DEFAULT NULL,
  `dienthoai` VARCHAR(1000) NULL DEFAULT NULL,
  `email` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 404
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Noingoaithat`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Noingoaithat` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Noingoaithat` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 422
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Phongthuy`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Phongthuy` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Phongthuy` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 432
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Tintuc`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Tintuc` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Tintuc` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 464
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `batdongsan`.`Wiki`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `batdongsan`.`Wiki` ;

CREATE TABLE IF NOT EXISTS `batdongsan`.`Wiki` (
  `Id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(1000) NULL DEFAULT NULL,
  `tieude` VARCHAR(1000) NULL DEFAULT NULL,
  PRIMARY KEY (`Id`))
ENGINE = InnoDB
AUTO_INCREMENT = 434
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
