//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MISA.WEB08.AMIS.API.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MISAResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MISAResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MISA.WEB08.AMIS.API.Resources.MISAResource", typeof(MISAResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SecretConnectionString.
        /// </summary>
        public static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EmployeeCode is existed, please try another code.
        /// </summary>
        public static string DevMsg_DuplicatedCode {
            get {
                return ResourceManager.GetString("DevMsg_DuplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sever has error when try to do this request..
        /// </summary>
        public static string DevMsg_Exception {
            get {
                return ResourceManager.GetString("DevMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some fileds of this request is not accepted.
        /// </summary>
        public static string DevMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("DevMsg_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e002.
        /// </summary>
        public static string MoreInfo_DupplicatedCode {
            get {
                return ResourceManager.GetString("MoreInfo_DupplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e001.
        /// </summary>
        public static string MoreInfo_Exception {
            get {
                return ResourceManager.GetString("MoreInfo_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://openapi.misa.com/error-code/e003.
        /// </summary>
        public static string MoreInfo_ValidateFailed {
            get {
                return ResourceManager.GetString("MoreInfo_ValidateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_DeleteOneRecord.
        /// </summary>
        public static string ProcDeleteOneEmployee {
            get {
                return ResourceManager.GetString("ProcDeleteOneEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_department_GetAll.
        /// </summary>
        public static string ProcGetAllDepartment {
            get {
                return ResourceManager.GetString("ProcGetAllDepartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_GetAll.
        /// </summary>
        public static string ProcGetAllEmployee {
            get {
                return ResourceManager.GetString("ProcGetAllEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_positions_GetAll.
        /// </summary>
        public static string ProcGetAllPosition {
            get {
                return ResourceManager.GetString("ProcGetAllPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_GetDuplicateCode.
        /// </summary>
        public static string ProcGetDupplicateCode {
            get {
                return ResourceManager.GetString("ProcGetDupplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_GetByID.
        /// </summary>
        public static string ProcGetEmployeeByID {
            get {
                return ResourceManager.GetString("ProcGetEmployeeByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_GetPaging.
        /// </summary>
        public static string ProcGetEmployeeFilter {
            get {
                return ResourceManager.GetString("ProcGetEmployeeFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_GetMaxCode.
        /// </summary>
        public static string ProcGetMaxEmployeeCode {
            get {
                return ResourceManager.GetString("ProcGetMaxEmployeeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_PostOneRecord.
        /// </summary>
        public static string ProcPostNewEmployee {
            get {
                return ResourceManager.GetString("ProcPostNewEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proc_employee_PutOneRecord.
        /// </summary>
        public static string ProcPutOneEmployee {
            get {
                return ResourceManager.GetString("ProcPutOneEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mã nhân viên đã tồn tại trong hệ thống, vui lòng sử dụng mã khác.
        /// </summary>
        public static string UserMsg_DuplicatedCode {
            get {
                return ResourceManager.GetString("UserMsg_DuplicatedCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có lỗi xảy ra, vui lòng liên hệ với MISA để được hỗ trợ..
        /// </summary>
        public static string UserMsg_Exception {
            get {
                return ResourceManager.GetString("UserMsg_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Có một hoặc nhiều trường dữ liệu bị lỗi, vui lòng kiểm tra lại..
        /// </summary>
        public static string UserMsg_ValidateFailed {
            get {
                return ResourceManager.GetString("UserMsg_ValidateFailed", resourceCulture);
            }
        }
    }
}
